project:
  type: book

book:
  title: "Dynamic Selection of Parallel Portfolio of Algorithms for Solving Combinatorial Problems"
  author: 
    - name: "Haniye Kashgarani"
      affiliation: "University of Wyoming"
      email: "hkashgar@uwyo.edu"
    - name: "Advisor: Dr. Lars Kotthoff"
      email: "larsko@uwyo.edu"
  date: "December 4, 2024"
  repo-url: "https://github.com/haniyeka/dissertation-website"
  sidebar:
    style: "floating"
    collapse-level: 1
    border: true
    search: true
  page-footer:
    center: "[Website](https://haniyeka.github.io) | [GitHub](https://github.com/haniyeka) | [UWYO-Mallet](https://github.com/uwyo-mallet)"
    right: Built with [Quarto](https://quarto.org/).
    background: "#f8f9fa"
  chapters:
    - index.qmd
    - chapters/chapter1/Introduction.qmd
    - chapters/chapter2/Background.qmd
    - chapters/chapter3/IsAlgorithmSelectionWorthItComparingSelectingSingleAlgorithmsandParallelExecution.qmd
    - chapters/chapter4/AutomaticParallelPortfolioSelection.qmd
    - chapters/chapter5/RevisitingParallelPortfolioSelectionwithKLDivergence.qmd
    - chapters/chapter6/ParallelPortfolioSelectionwithParallelDataTraining.qmd
    - chapters/chapter7/DiscussionandConclusion.qmd
    - chapters/appendices/appendixA.qmd
bibliography: sample.bib
format:
  html:
    theme:
      light: [default]
    mathjax: true
    fontsize: "15px"
    linestretch: 1.6
    mainfont: "Roboto"
    monofont: "Fira Mono"
    smooth-scroll: true
    toc-depth: 3
    code-link: true
    code-tools:
      toggle: true
    code-fold: false
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    reference-location: margin
    mermaid:
      theme: neutral

pdf:
  documentclass: book
  number-sections: true
  pdf-engine: xelatex
